### ISSUE TITLE
[QA] Device compatibility

### ISSUE THREAD

**Issue by ferndot** [joshua-s/coronavirus-diary#15]
Considering that some of the populations especially at risk may also have older devices, widespread device compatibility is highly important and should be a part of our QA process.

Android version market share in the USA: https://gs.statcounter.com/android-version-market-share/mobile-tablet/united-states-of-america
iOS version market share in the USA: https://gs.statcounter.com/os-version-market-share/ios/mobile-tablet/united-states-of-america

**Flutter's [minimum requirements](https://flutter.dev/docs/resources/faq#what-devices-and-os-versions-does-flutter-run-on):**
- Mobile operating systems: Android Jelly Bean, v16, 4.1.x or newer, and iOS 8 or newer.
- Mobile hardware: iOS devices (iPhone 4S or newer) and ARM Android devices.

**Comment by mmcc007** [comment]
Sylph can be used to run integration tests on hundreds of devices including older devices:
https://github.com/mmcc007/sylph
Works with codemagic.
Can submit PR if interested.

Here is a sample config file:
```
tmp_dir: /tmp/sylph
artifacts_dir: /tmp/sylph_artifacts
sylph_timeout: 720 # seconds approx
concurrent_runs: true

project_name: coronavirus-diary
default_job_timeout: 10 # minutes, set at project creation

device_pools:

  - pool_name: android devices
    pool_type: android
    devices:
      - name: Google Pixel 2
        model: Google Pixel 2
        os: 8.0.0
      - name: LG G Flex (AT&T) # oldest android OS supported by device farm
        model: D950
        os: 4.2.2

  - pool_name: ios devices
    pool_type: ios
    devices:
      - name: Apple iPhone X
        model: A1865
        os: 12.0
      - name: Apple iPhone 4S # oldest ios device supported on device farm
        model: A1387
        os: 9.3.5

test_suites:

  - test_suite: integration test
    main: test_driver/smoke_workflow.dart
    tests:
      - test_driver/smoke_workflow_test.dart
    pool_names:
      - android devices
      - ios devices
    job_timeout: 15 # minutes, set per job, over-rides default job timeout above

```
